### ISSUE TITLE
Another Hexagonal Minecraft

### ISSUE THREAD

**Issue by Panzerschrek** [Martomate/Hexacraft#73]
Hi!
This is not a real issue. I just want to mention that i had developed a while ago [something similar](https://github.com/Panzerschrek/Hex). It has pretty large world consisting of hexagonal prisms. Textures are also hex-filtered.

**Comment by Martomate** [comment]
Cool! I just downloaded and ran the release from 2017 and it's actually better than I expected. It's nice to see that you used hexagons in so many places, even on the top of blocks and the shapes of the clouds. I also noticed that you have vertical slabs which is something I've been considering too. The water is also quite similar to the water in Hexacraft in that it's a limited resource. All in all, it's a nice little project!
